### ISSUE TITLE
Minimal Documentation

### ISSUE THREAD

**Issue by elyobo** [savonrb/sekken#24]
I realise that this is experimental, but the current documentation doesn't cover even the most minimal usage, e.g. how to make a call.  That would make it much easier to test this out rather than trying to look through the code and infer the expected usage!

On a vaguely related note, there has been very little activity on Sekken and Savon; are both projects still maintained?  We're looking at a ruby project that needs to hook into some legacy SOAP services and unfortunately Savon 2 can't handle them property (lack of import support), which leaves us using Savon 2 while constructing our own requests using gyoku (painful) or exploring Sekken (which might work, but given the lack of documentation it's hard to know where to begin).

**Comment by tjarratt** [comment]
Hey @elyobo, that's a great question. There had been some work in flight that Rubiii had when I started maintaining Savon to create "Savon 3", which we ended up extract into Sekken when it became clear that maintaining Savon v2 was a more valuable activity, and we still had a lot of issues.

I've become increasingly busy since then, both in real life and in OSS life, so I haven't had as much time to contribute to Savon as I would have liked.

The real, honest answer I can tell you is that if you're writing Ruby and you need to interact with SOAP services, be prepared to spend a LOT of time debugging issues. Savon has never been a perfect, turn-key solution for 100% of all SOAP services. It handles ... quite a few well, but there are a tiny little jagged edges in the SOAP spec that Savon has not handled gracefully.

This has been a painful issue for the community for a long time. People find Savon, see how it works, fall in love with the API, then get frustrated that it won't perform operations for their WSDL correctly. It's sad for me, and it's sad for the community too.

At my last company, I had to interact with some services from a vendor that were exposed via SOAP. I spent the better part of a year fixing up Savon's multipart support, debugging issues in production and generally growing my understanding of SOAP day after day. If you need to interact with a SOAP service, you should either find an incredibly mature library that can handle your operations as well as SOAP-UI, or be prepared to do a lot of work to make a gem like Savon work. That's just the cold, hard truth of open source software. 

Unless someone goes and looks at every single part of the SOAP spec (and I've tried to, on multiple occasions, for various bits and pieces of WSDL parsing, request generating and response parsing logic), Savon will never be 100% completely up to spec.

I'd be happy to merge contributions from the community, or to find someone that's willing to maintain the project, but my sense is that few people are willing to do so for free. Ideally I'd like to find a company that uses Savon that wants to invest in it, but I think most people interact minimally with SOAP services and then run away as fast as they can.

¯\_(ツ)_/¯

Hope this helped!

¯\_(ツ)_/¯

**Comment by elyobo** [comment]
Thanks for such a thoughtful and thorough response @tjarratt.

I wish that I could be of more assistance but as you point out the SOAP spec is scary and added to that I'm not at all experienced with ruby.

In my case we've managed to convince the team that we need a newer, more functional, non-SOAP service so I no longer have need of this anyway (and in the interim I managed to beat node-soap into working with the parts I need, working around similar schema issues, which now provides a proxy until the new service is available).

It seems like the world is moving away from SOAP outside of legacy applications, but hopefully there will be someone out there able to fund further development on this for those that are stuck with them but want to use ruby to interact with them.
